{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
{{- $nativeEnabled := eq (include "dataflow.metadataPostgresNativeEnabled" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "dataflow.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dataflow.labels" . | nindent 4 }}
type: Opaque
data:
  WHODB_SESSION_ENCRYPTION_KEY: {{ .Values.session.encryptionKey | b64enc | quote }}
  {{- if and (not $nativeEnabled) .Values.metadata.dsn }}
  WHODB_METADATA_DSN: {{ .Values.metadata.dsn | b64enc | quote }}
  {{- end }}
  {{- if .Values.metadata.sessionDsn }}
  WHODB_SESSION_DSN: {{ .Values.metadata.sessionDsn | b64enc | quote }}
  {{- end }}
{{- end }}
